#Custom INCAR parameters for PDOS calculations
ALGO = "Normal"
EDIFF = 1e-06
ENCUT = 520.0
ISMEAR = 0
ISPIN = 2
ICHARG = 1
LCHARG = true
LORBIT = 11
NEDOS = 2000
LWAVE = false
PREC = "Accurate"
SIGMA = 0.05
